import asyncio
import sys
import os
from datetime import date

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import AsyncSessionLocal, engine, Base
import app.models
from app.core.security import get_password_hash
from app.models.auth import Role, Permission, Organization, User
from app.models.standards import Standard, StandardStatus, CertificationRequirement, StandardVersion, Amendment


async def seed_data():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        print("[START] Starting database seeding...")
        
        # 1. Seed Roles
        roles = {
            "SUPER_ADMIN": "Full System Administrator access across all tenant organizations",
            "ORG_ADMIN": "Organization Administrator with full internal procurement control",
            "PROCUREMENT_OFFICER": "Procurement Officer responsible for tender analysis and standards mapping",
            "APPROVER": "Executive Approver for compliance reports and tender sign-offs",
            "AUDITOR": "Read-only Auditor access for compliance reporting and audit verification"
        }
        
        from sqlalchemy import select
        role_objs = {}
        for r_name, r_desc in roles.items():
            stmt = select(Role).where(Role.name == r_name)
            res = await session.execute(stmt)
            existing_role = res.scalar_one_or_none()
            if not existing_role:
                role = Role(name=r_name, description=r_desc)
                session.add(role)
                role_objs[r_name] = role
            else:
                role_objs[r_name] = existing_role
        await session.flush()
        print("[OK] Seeded Roles.")

        # 2. Seed Default Organization
        stmt = select(Organization).where(Organization.code == "mohua-gov-in")
        res = await session.execute(stmt)
        org = res.scalar_one_or_none()
        if not org:
            org = Organization(
                name="Ministry of Housing and Urban Affairs (MoHUA)",
                code="mohua-gov-in",
                domain="mohua.gov.in",
                contact_email="procurement@mohua.gov.in",
                address="Nirman Bhawan, New Delhi"
            )
            session.add(org)
            await session.flush()
        print("[OK] Seeded Default Organization.")

        # 3. Seed Default Admin User
        stmt = select(User).where(User.email == "admin@mohua.gov.in")
        res = await session.execute(stmt)
        admin_user = res.scalar_one_or_none()
        if not admin_user:
            admin_user = User(
                email="admin@mohua.gov.in",
                hashed_password=get_password_hash("Admin123!"),
                full_name="Rajesh Kumar",
                designation="Chief Procurement Officer",
                organization_id=org.id,
                roles=[role_objs["SUPER_ADMIN"], role_objs["ORG_ADMIN"]]
            )
            session.add(admin_user)
            await session.flush()
        print("[OK] Seeded Admin User (admin@mohua.gov.in / Admin123!).")

        # 4. Seed Sample & CRS Mandatory BIS Standards
        sample_standards = [
            {
                "is_number": "IS 13252(Part 1):2010",
                "title": "Information Technology Equipment - Safety - Part 1: General Requirements",
                "scope": "Mandatory safety specification for Automatic Data Processing Machines, Laptops, Notebooks, Tablets, Mobile Phones, Printers, Scanners, POS Terminals, Power Adaptors, and Hard Disk Drives under BIS CRS.",
                "domain": "Electronics & Information Technology",
                "category": "Computers, Laptops, Mobile Phones & IT Peripherals",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2010, 4, 1),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["laptops", "notebooks", "tablets", "computers", "it equipment", "mobile phones", "safety"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS/IEC 62368-1:2023",
                "title": "Audio/Video, Information and Communication Technology Equipment - Part 1: Safety Requirements",
                "scope": "Latest hazard-based safety standard for Servers, High-End Laptops, Commercial Desktop PCs, Telecom Routers, Workstations, and Enterprise Network Switches under BIS CRS.",
                "domain": "Electronics & Information Technology",
                "category": "Computers, Servers & Enterprise IT Equipment",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2023, 3, 15),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["servers", "laptops", "desktops", "workstations", "routers", "switches", "ict equipment"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 616:2017",
                "title": "Audio, Video and Similar Electronic Apparatus - Safety Requirements",
                "scope": "Mandatory safety requirements for Amplifiers, Televisions, Bluetooth Speakers, Smart Speakers, Wireless Headphones, Video Games, and Power Adaptors under BIS CRS.",
                "domain": "Electronics & Information Technology",
                "category": "Audio, Video & Consumer Electronics",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2017, 9, 15),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["television", "audio", "video", "speakers", "headphones", "electronics", "safety"],
                "issuing_committee": "LITD 07 Audio, Video and Similar Electronic Apparatus",
                "ic_code": "LITD07"
            },
            {
                "is_number": "IS 16333 (Part 3) : 2022",
                "title": "Mobile Phone Handsets - Part 3: Indian Language Support for Mobile Phone Handsets - Specific Requirements",
                "scope": "Mandatory requirements for Indian Language support in Mobile Phone Handsets including input, display, and keypad layout specifications across 22 official scheduled languages.",
                "domain": "Electronics & Information Technology",
                "category": "Mobile Phones & Indian Language Peripherals",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 1, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["mobile phones", "indian language", "keypad", "indic script", "telecom", "smartphones"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 16046 (Part 1) : 2018",
                "title": "Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes - Nickel Systems",
                "scope": "Safety requirements for portable sealed secondary nickel cells and batteries used in portable electronics, IT peripherals, and emergency equipment.",
                "domain": "Electronics & Information Technology",
                "category": "Batteries & Portable Energy Storage",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2018, 7, 1),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["batteries", "nickel", "rechargeable", "power bank", "portable power"],
                "issuing_committee": "ETD 11 Secondary Cells and Batteries Committee",
                "ic_code": "ETD11"
            },
            {
                "is_number": "IS 16046 (Part 2) : 2018",
                "title": "Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes - Lithium Systems",
                "scope": "Mandatory safety specification for Sealed Secondary Lithium Cells and Batteries (Li-Ion & Li-Polymer) for use in Laptops, Mobile Phones, Tablets, Power Banks, and Wearables.",
                "domain": "Electronics & Information Technology",
                "category": "Batteries, Laptops & Mobile Power Banks",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2018, 7, 1),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["li-ion", "lithium battery", "laptop battery", "power bank", "mobile battery"],
                "issuing_committee": "ETD 11 Secondary Cells and Batteries Committee",
                "ic_code": "ETD11"
            },
            {
                "is_number": "IS 16242 (Part 1) : 2014",
                "title": "Uninterruptible Power Systems (UPS) - Part 1: General and Safety Requirements for UPS",
                "scope": "Mandatory safety specification for UPS systems, power inverters, and emergency battery backup units deployed in government IT data centers and offices.",
                "domain": "Electrical Engineering",
                "category": "UPS, Power Systems & Data Center Infrastructure",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2014, 5, 20),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["ups", "uninterruptible power", "inverter", "data center", "power supply"],
                "issuing_committee": "ETD 12 Power Electronics & UPS Systems",
                "ic_code": "ETD12"
            },
            {
                "is_number": "IS 17822 : 2022",
                "title": "Essential Requirement(s) for Security of CCTV Cameras and Network Video Recorders (NVR)",
                "scope": "Mandatory hardware security and encryption standards for CCTV Surveillance Cameras, IP Cameras, and NVRs deployed in government e-Procurement projects.",
                "domain": "Electronics & Information Technology",
                "category": "CCTV Security, Surveillance & Network Recorders",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 8, 14),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["cctv", "surveillance", "ip camera", "nvr", "security camera", "telecom"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 17904 : 2022",
                "title": "Smart Watches and Wearable Activity Trackers - Safety Requirements",
                "scope": "Mandatory safety and SAR compliance requirements for Smart Watches, Fitness Trackers, and Wearable Smart Devices under BIS CRS.",
                "domain": "Electronics & Information Technology",
                "category": "Smart Wearables & Consumer Electronics",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 11, 30),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["smart watch", "wearables", "fitness tracker", "smart device"],
                "issuing_committee": "LITD 07 Audio, Video and Similar Electronic Apparatus",
                "ic_code": "LITD07"
            },
            {
                "is_number": "IS 17926 : 2022",
                "title": "Safety Requirements for Virtual Reality (VR) and Augmented Reality (AR) Equipment",
                "scope": "Mandatory optical safety, thermal safety, and electromagnetic radiation standards for AR/VR Headsets, Smart Glasses, and Spatial Computing displays.",
                "domain": "Electronics & Information Technology",
                "category": "AR/VR Hardware & Next-Gen Display Devices",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 10, 15),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["virtual reality", "vr", "augmented reality", "ar headset", "smart glasses"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 14286 : 2019",
                "title": "Crystalline Silicon Terrestrial Photovoltaic (PV) Modules - Design Qualification and Type Approval",
                "scope": "Mandatory quality and design qualification specification for Solar PV Modules under MNRE and BIS Quality Control Orders.",
                "domain": "Electrical Engineering",
                "category": "Solar Photovoltaic Modules & Renewable Energy",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2019, 6, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["solar pv", "solar panel", "photovoltaic", "renewable energy"],
                "issuing_committee": "ETD 28 Solar Photovoltaic Energy Systems",
                "ic_code": "ETD28"
            },
            {
                "is_number": "IS 18112 : 2022",
                "title": "Specification for Television Sets with Built-in Satellite Tuners",
                "scope": "Indian Standard for Direct-to-Home (DTH) TV sets having built-in satellite tuners to receive Free-to-Air TV and Radio channels without a separate Set Top Box.",
                "domain": "Electronics & Information Technology",
                "category": "Television & Broadcast Receivers",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 12, 1),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["television", "smart tv", "tuner", "telecom", "set top box"],
                "issuing_committee": "LITD 06 Audio, Video and Multimedia Systems",
                "ic_code": "LITD06"
            },
            {
                "is_number": "IS 10322 (Part 5/Sec 3) : 2012",
                "title": "Luminaires - Part 5: Particular Requirements - Section 3: Luminaires for Road and Street Lighting",
                "scope": "Mandatory safety and operational specification for LED Street Light Luminaires, Highway Lighting, and Outdoor Municipal Fixtures.",
                "domain": "Electrical Engineering",
                "category": "Lighting, LED Luminaires & Street Lighting",
                "sector": "lighting",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2012, 11, 20),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["led", "luminaires", "street lighting", "lighting", "floodlights"],
                "issuing_committee": "ETD 24 Illumination Engineering and Luminaires",
                "ic_code": "ETD24"
            },
            {
                "is_number": "IS 15885 (Part 2/Sec 13) : 2012",
                "title": "Lamp Controlgear - Part 2-13: Particular Requirements for Electronic Controlgear for LED Modules",
                "scope": "Mandatory BIS CRS safety specification for electronic LED drivers, power supply controlgear, and constant-current drivers used in commercial lighting.",
                "domain": "Electrical Engineering",
                "category": "LED Drivers & Power Supplies",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2012, 8, 15),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["led driver", "controlgear", "power supply", "led module"],
                "issuing_committee": "ETD 24 Illumination Engineering and Luminaires",
                "ic_code": "ETD24"
            },
            {
                "is_number": "IS 1293 : 2019",
                "title": "Plugs and Socket-Outlets for Household and Similar Purposes of Rated Voltage up to and including 250V",
                "scope": "Mandatory safety standard for 6A/16A electrical plugs, sockets, power extension cords, and AC adaptors used with laptops and appliances.",
                "domain": "Electrical Engineering",
                "category": "Plugs, Sockets & Electrical Accessories",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2019, 10, 1),
                "certification_requirement": CertificationRequirement.ISI,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["plug", "socket", "power cord", "adapter", "electrical"],
                "issuing_committee": "ETD 14 Electrical Wiring Accessories",
                "ic_code": "ETD14"
            },
            {
                "is_number": "IS 694 : 2010",
                "title": "Polyvinyl Chloride Insulated Cables for Working Voltages up to and Including 1100 V",
                "scope": "Standard specification for PVC insulated single-core and multi-core copper/aluminium power cables used in office wiring and computer networking infrastructure.",
                "domain": "Electrical Engineering",
                "category": "Electrical Cables & Networking Conductors",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2010, 5, 12),
                "certification_requirement": CertificationRequirement.ISI,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["cable", "pvc cable", "copper wire", "networking wire", "electrical cable"],
                "issuing_committee": "ETD 09 Cables and Wires",
                "ic_code": "ETD09"
            },
            {
                "is_number": "IS/ISO 9001 : 2015",
                "title": "Quality Management Systems - Requirements",
                "scope": "International benchmark standard for Quality Management Systems required for OEMs and bidders participating in Indian Government tenders under GFR 2017.",
                "domain": "General Standards",
                "category": "Quality Management & Vendor Accreditation",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2015, 9, 23),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["iso 9001", "quality management", "qms", "vendor audit"],
                "issuing_committee": "MSD 02 Quality and Reliability Management",
                "ic_code": "MSD02"
            },
            {
                "is_number": "IS/ISO/IEC 27001 : 2022",
                "title": "Information Security, Cybersecurity and Privacy Protection - Information Security Management Systems",
                "scope": "Mandatory cybersecurity baseline standard for IT vendors, software developers, and cloud service providers bidding on e-Procurement portals.",
                "domain": "Electronics & Information Technology",
                "category": "Cybersecurity, Cloud & Data Protection",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 10, 25),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["iso 27001", "cybersecurity", "information security", "cloud", "data protection"],
                "issuing_committee": "LITD 17 Information Security and Data Privacy",
                "ic_code": "LITD17"
            },
            {
                "is_number": "IS 17025 : 2017",
                "title": "General Requirements for the Competence of Testing and Calibration Laboratories",
                "scope": "Governing standard for NABL accredited laboratories performing type tests and compliance verification for BIS mandatory standards.",
                "domain": "Testing & Calibration",
                "category": "NABL Laboratory Accreditation",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2017, 11, 30),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["nabl", "testing laboratory", "type test", "calibration", "accreditation"],
                "issuing_committee": "MSD 03 Conformity Assessment Committee",
                "ic_code": "MSD03"
            },
            {
                "is_number": "IS 15147 : 2002",
                "title": "Information Technology - Telecommunications and Information Exchange Between Systems",
                "scope": "Technical requirements for enterprise local area networks (LAN), Ethernet switches, and optical fiber interconnectivity in government offices.",
                "domain": "Electronics & Information Technology",
                "category": "Networking & LAN Infrastructure",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2002, 5, 10),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["lan", "ethernet", "networking", "telecom", "switch", "router"],
                "issuing_committee": "LITD 18 Telecommunications and Broadband",
                "ic_code": "LITD18"
            },
            {
                "is_number": "IS 14886 : 2000",
                "title": "Information Technology - Software Process Assessment and Quality Standards",
                "scope": "Standard quality framework for government software procurement, ERP deployment, and custom application development.",
                "domain": "Electronics & Information Technology",
                "category": "Software Engineering & Quality Assurance",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2000, 3, 15),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["software", "procurement", "quality assurance", "it services"],
                "issuing_committee": "LITD 15 Software and System Engineering",
                "ic_code": "LITD15"
            },
            {
                "is_number": "IS 15300 : 2003",
                "title": "Information Technology - Security Techniques - Information Security Management",
                "scope": "Baseline information security controls for data centers, cloud infrastructure, and e-governance databases.",
                "domain": "Electronics & Information Technology",
                "category": "Cybersecurity & Data Center Infrastructure",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2003, 8, 20),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["data center", "cloud", "security", "database", "e-governance"],
                "issuing_committee": "LITD 17 Information Security and Data Privacy",
                "ic_code": "LITD17"
            },
            {
                "is_number": "IS 15888 : 2011",
                "title": "Information Technology - Generic Cabling for Customer Premises",
                "scope": "Structured copper and optical fiber cabling specifications for commercial and government office networks.",
                "domain": "Electronics & Information Technology",
                "category": "Structured Network Cabling",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2011, 4, 12),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["cabling", "cat6", "fiber optic", "structured cabling", "network"],
                "issuing_committee": "LITD 18 Telecommunications and Broadband",
                "ic_code": "LITD18"
            },
            {
                "is_number": "IS 16400 : 2015",
                "title": "Electronic Display Units - Visual Comfort and Safety Guidelines",
                "scope": "Visual ergonomic, flicker-free, and blue-light filtration safety standards for desktop PC monitors and commercial displays.",
                "domain": "Electronics & Information Technology",
                "category": "Monitors & Electronic Displays",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2015, 11, 5),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["monitor", "display", "screen", "visual ergonomics", "desktop"],
                "issuing_committee": "LITD 07 Audio, Video and Similar Electronic Apparatus",
                "ic_code": "LITD07"
            },
            {
                "is_number": "IS 16860 : 2021",
                "title": "Hardware Security Specification for Automatic Data Processing Systems and Enterprise Servers",
                "scope": "Mandatory TPM 2.0 cryptographic chip and Secure Boot hardware requirement for commercial desktop PCs, workstations, and servers.",
                "domain": "Electronics & Information Technology",
                "category": "Enterprise Servers & Computer Hardware",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2021, 9, 18),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["tpm", "secure boot", "server", "hardware security", "desktop pc"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 17950 : 2023",
                "title": "Commercial Laptops and Notebook Computers - Technical Guidelines & Energy Efficiency",
                "scope": "Performance, battery longevity, shock resistance, and Bureau of Energy Efficiency (BEE) star rating specifications for government laptop tenders.",
                "domain": "Electronics & Information Technology",
                "category": "Commercial Laptop & Notebook Computers",
                "sector": "laptops",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2023, 5, 20),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["laptop", "notebook", "battery life", "bee star rating", "portable pc"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 15000 : 2013",
                "title": "Biometric Data Interchange Formats - Fingerprint and Iris Sensor Specifications",
                "scope": "Technical interface and security requirements for UIDAI Aadhaar compliant biometric fingerprint scanners and iris readers.",
                "domain": "Electronics & Information Technology",
                "category": "Biometric Authentication & Iris Scanners",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2013, 2, 28),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["biometric", "fingerprint scanner", "iris reader", "aadhaar", "uidai"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 16101 : 2012",
                "title": "General Lighting - LEDs and LED Modules - Terms and Definitions",
                "scope": "Terminological and classification framework for all solid-state LED lighting modules, luminaires, and electronic drivers.",
                "domain": "Electrical Engineering",
                "category": "LED Lighting Standard Terms",
                "sector": "lighting",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2012, 6, 15),
                "certification_requirement": CertificationRequirement.VOLUNTARY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["led", "solid state lighting", "lighting definitions"],
                "issuing_committee": "ETD 24 Illumination Engineering and Luminaires",
                "ic_code": "ETD24"
            },
            {
                "is_number": "IS 16103 (Part 1) : 2012",
                "title": "Led Modules for General Lighting - Safety Specifications",
                "scope": "Safety specifications for printed circuit board LED modules used in commercial luminaires and street lighting.",
                "domain": "Electrical Engineering",
                "category": "LED Modules & Electronic Board Safety",
                "sector": "lighting",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2012, 8, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["led module", "pcb", "led safety", "luminaire"],
                "issuing_committee": "ETD 24 Illumination Engineering and Luminaires",
                "ic_code": "ETD24"
            },
            {
                "is_number": "IS 16107 (Part 2/Sec 1) : 2012",
                "title": "Luminaires Performance - Particular Requirements for LED Luminaires",
                "scope": "Lumen maintenance, optical efficacy (lm/W), and color rendering index (CRI) standards for commercial and outdoor LED fixtures.",
                "domain": "Electrical Engineering",
                "category": "LED Luminaire Optical Performance",
                "sector": "lighting",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2012, 10, 22),
                "certification_requirement": CertificationRequirement.VOLUNTARY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["optical performance", "lumens per watt", "cri", "led luminaire"],
                "issuing_committee": "ETD 24 Illumination Engineering and Luminaires",
                "ic_code": "ETD24"
            },
            {
                "is_number": "IS 13703 (Part 1) : 1993",
                "title": "Low Voltage Fuses for Voltage Not Exceeding 1000 V AC or 1500 V DC",
                "scope": "Overcurrent protection fuse standards for power distribution panels, data centers, and industrial UPS installations.",
                "domain": "Electrical Engineering",
                "category": "Electrical Fuses & Panel Protection",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(1993, 7, 14),
                "certification_requirement": CertificationRequirement.ISI,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["fuse", "circuit protection", "distribution panel", "low voltage"],
                "issuing_committee": "ETD 39 High Voltage Switchgear and Controlgear",
                "ic_code": "ETD39"
            },
            {
                "is_number": "IS 2026 (Part 1) : 2011",
                "title": "Power Transformers - General Requirements",
                "scope": "Standard specification for oil-immersed and dry-type distribution transformers used in government infrastructure electrification.",
                "domain": "Electrical Engineering",
                "category": "Transformers & Power Grid Equipment",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2011, 3, 30),
                "certification_requirement": CertificationRequirement.ISI,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["transformer", "power transformer", "grid", "distribution"],
                "issuing_committee": "ETD 16 Transformers Committee",
                "ic_code": "ETD16"
            },
            {
                "is_number": "IS 8623 (Part 1) : 1993",
                "title": "Low-Voltage Switchgear and Controlgear Assemblies - Requirements for Type-Tested and Partially Type-Tested Assemblies",
                "scope": "Standard requirements for main power distribution boards (PDB), sub-distribution boards, and MCC panels in smart cities.",
                "domain": "Electrical Engineering",
                "category": "Low Voltage Switchgear & PDB Panels",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(1993, 11, 15),
                "certification_requirement": CertificationRequirement.ISI,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["switchgear", "pdb panel", "controlgear", "distribution board"],
                "issuing_committee": "ETD 07 High Voltage Switchgear and Controlgear",
                "ic_code": "ETD07"
            },
            {
                "is_number": "IS 3043 : 2018",
                "title": "Code of Practice for Earthing",
                "scope": "Mandatory technical guidelines for chemical earthing, equipment grounding, and lightning protection in IT server rooms and hospitals.",
                "domain": "Electrical Engineering",
                "category": "Electrical Grounding & Earthing Systems",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2018, 5, 25),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["earthing", "grounding", "lightning protection", "server room earthing"],
                "issuing_committee": "ETD 30 Electrical Installations",
                "ic_code": "ETD30"
            },
            {
                "is_number": "IS/IEC 60529 : 2001",
                "title": "Degrees of Protection Provided by Enclosures (IP Code)",
                "scope": "Standard classification of Ingress Protection (IP55, IP65, IP66, IP67, IP68) against dust, solid objects, and water ingress for electrical and IT enclosures.",
                "domain": "General Engineering",
                "category": "Ingress Protection (IP Rating) Enclosures",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2001, 2, 10),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["ip rating", "ingress protection", "ip66", "ip65", "weatherproof enclosure"],
                "issuing_committee": "ETD 14 Electrical Accessories",
                "ic_code": "ETD14"
            },
            {
                "is_number": "IS 7098 (Part 1) : 1988",
                "title": "Cross-Linked Polyethylene (XLPE) Insulated PVC Sheathed Cables for Working Voltages up to and Including 1100 V",
                "scope": "Standard specification for heavy-duty XLPE underground armored power cables used in industrial facilities and municipal street lighting.",
                "domain": "Electrical Engineering",
                "category": "Armored Power Cables & XLPE Wiring",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(1988, 12, 1),
                "certification_requirement": CertificationRequirement.ISI,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["xlpe cable", "armored cable", "power cable", "underground cable"],
                "issuing_committee": "ETD 09 Cables and Wires",
                "ic_code": "ETD09"
            },
            {
                "is_number": "IS 15477 : 2004",
                "title": "Information Technology - Security Techniques - Evaluation Criteria for IT Security",
                "scope": "Common Criteria (ISO 15408) evaluation standards for operating system security, hardware security modules (HSM), and biometric devices.",
                "domain": "Electronics & Information Technology",
                "category": "IT Security Evaluation & Common Criteria",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2004, 9, 14),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["common criteria", "it security", "evaluation criteria", "hsm"],
                "issuing_committee": "LITD 17 Information Security and Data Privacy",
                "ic_code": "LITD17"
            },
            {
                "is_number": "IS 16402 : 2015",
                "title": "Essential Requirements for High Density Flash Storage and Solid State Drives (SSD)",
                "scope": "Quality, data retention, endurance (TBW), and shock tolerance specifications for NVMe and SATA Solid State Drives (SSD) in laptops and servers.",
                "domain": "Electronics & Information Technology",
                "category": "Solid State Drives & Storage Hardware",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2015, 7, 21),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["ssd", "nvme", "solid state drive", "hard disk", "storage"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 17500 : 2021",
                "title": "Technical Requirements for Smart Meters and Advanced Metering Infrastructure (AMI)",
                "scope": "Mandatory communications protocol, cyber security, and metrological standards for Smart Electricity Meters and AMI gateway systems.",
                "domain": "Electrical Engineering",
                "category": "Smart Meters & Power Grid Communications",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2021, 4, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["smart meter", "ami", "smart grid", "electricity meter"],
                "issuing_committee": "ETD 13 Electrical Instruments and Metering",
                "ic_code": "ETD13"
            },
            {
                "is_number": "IS 16000 : 2012",
                "title": "Medical Electrical Equipment - Part 1: General Requirements for Basic Safety and Essential Performance",
                "scope": "Mandatory medical safety standard for ICU Ventilators, Patient Monitors, Anesthesia Machines, and Surgical Equipment.",
                "domain": "Medical Devices",
                "category": "ICU Ventilators & Medical Safety Equipment",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2012, 1, 15),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["medical device", "icu ventilator", "patient monitor", "hospital equipment"],
                "issuing_committee": "MHD 03 Medical Electrical Equipment",
                "ic_code": "MHD03"
            },
            {
                "is_number": "IS 13450 (Part 1) : 2018",
                "title": "Medical Devices - Quality Management Systems - Requirements for Regulatory Purposes",
                "scope": "Quality management requirements (ISO 13485 equivalent) for medical device OEMs bidding on government healthcare procurement.",
                "domain": "Medical Devices",
                "category": "Medical Device Quality Accreditation",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2018, 3, 22),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["iso 13485", "medical device quality", "healthcare procurement"],
                "issuing_committee": "MHD 03 Medical Electrical Equipment",
                "ic_code": "MHD03"
            },
            {
                "is_number": "IS 17400 : 2020",
                "title": "Safety Guidelines for Personal Protective Equipment (PPE) in High Voltage Electrical Works",
                "scope": "Dielectric insulation, arc flash safety, and mechanical puncture strength standards for electrical safety gloves, boots, and face shields.",
                "domain": "Electrical Engineering",
                "category": "Electrical Safety PPE & High Voltage Gear",
                "sector": "lighting",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2020, 6, 18),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["electrical safety", "ppe", "dielectric glove", "arc flash"],
                "issuing_committee": "ETD 30 Electrical Installations",
                "ic_code": "ETD30"
            },
            {
                "is_number": "IS 17600 : 2021",
                "title": "Electric Vehicle (EV) Conductive AC Charging Systems - General Requirements",
                "scope": "Mandatory safety, connector geometry, and communication standards for EV AC Charging Stations (Type-2 / Bharat AC-001).",
                "domain": "Electrical Engineering",
                "category": "EV Chargers & Electric Vehicle Infrastructure",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2021, 10, 5),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["ev charger", "electric vehicle", "bharat ac001", "charging station"],
                "issuing_committee": "ETD 51 Electric Vehicles Committee",
                "ic_code": "ETD51"
            },
            {
                "is_number": "IS 17601 : 2021",
                "title": "Electric Vehicle (EV) Conductive DC Fast Charging Stations - Safety & Performance",
                "scope": "Mandatory safety and communication protocol (CCS2 / CHAdeMO) for EV DC Fast Charging Stations (15kW to 150kW).",
                "domain": "Electrical Engineering",
                "category": "EV DC Fast Chargers & Charging Hubs",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2021, 10, 5),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["ev dc charger", "ccs2", "fast charger", "electric vehicle"],
                "issuing_committee": "ETD 51 Electric Vehicles Committee",
                "ic_code": "ETD51"
            },
            {
                "is_number": "IS 15478 (Part 1) : 2004",
                "title": "Information Technology - Office Equipment - Scanners and Image Capturing Devices",
                "scope": "Performance and optical resolution standards for flatbed, sheetfed, and document scanners used in e-Governance offices.",
                "domain": "Electronics & Information Technology",
                "category": "Printers, Scanners & Image Capture",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2004, 6, 12),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["scanner", "document scanner", "optical resolution", "peripherals"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 15479 : 2004",
                "title": "Information Technology - Office Equipment - Multifunction Printers (MFP)",
                "scope": "Safety, energy consumption, and print throughput standards for laser multifunction printers (MFP) and copiers.",
                "domain": "Electronics & Information Technology",
                "category": "Printers, Scanners & Image Capture",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2004, 8, 18),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["printer", "multifunction printer", "mfp", "laser printer"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 15889 : 2011",
                "title": "Information Technology - Financial Transaction Cards and POS Terminals",
                "scope": "EMV Level 1 and Level 2 security standards for Point-of-Sale (POS) card reader terminals deployed in public utilities.",
                "domain": "Electronics & Information Technology",
                "category": "POS Terminals & Smart Card Readers",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2011, 11, 30),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["pos terminal", "card reader", "emv", "smart card", "pos"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 16861 : 2021",
                "title": "Enterprise Cloud Server Hardware - Reliability and Environmental Qualification",
                "scope": "Thermal stress, vibration, and redundant power supply (1+1 RPS) qualification for 1U/2U rackmount enterprise servers.",
                "domain": "Electronics & Information Technology",
                "category": "Enterprise Servers & Computer Hardware",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2021, 12, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["rack server", "cloud server", "1u server", "redundant power", "enterprise hardware"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 17450 : 2020",
                "title": "Optical Fiber Cables for Telecommunications - Part 1: Generic Specification",
                "scope": "Armored optical fiber cable specifications (Single-Mode ITU-T G.652D) for BharatNet broadband and WAN networks.",
                "domain": "Electronics & Information Technology",
                "category": "Optical Fiber Cables & Telecom WAN",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2020, 2, 14),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["optical fiber", "fiber cable", "single mode fiber", "bharatnet", "telecom"],
                "issuing_committee": "LITD 18 Telecommunications and Broadband",
                "ic_code": "LITD18"
            },
            {
                "is_number": "IS 17451 : 2020",
                "title": "Fiber Optic Connectors and Patch Cords for Telecommunication Networks",
                "scope": "Insertion loss, return loss, and mechanical durability standards for LC/SC/ST fiber patch cords and connectors.",
                "domain": "Electronics & Information Technology",
                "category": "Optical Fiber Cables & Telecom WAN",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2020, 4, 19),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["patch cord", "lc connector", "fiber connector", "telecom"],
                "issuing_committee": "LITD 18 Telecommunications and Broadband",
                "ic_code": "LITD18"
            },
            {
                "is_number": "IS 17550 : 2021",
                "title": "Smart Card Readers and Interface Devices for National e-ID Programs",
                "scope": "ISO 7816 and Contactless ISO 14443 smart card reader standards for National ID and e-Passport verification.",
                "domain": "Electronics & Information Technology",
                "category": "POS Terminals & Smart Card Readers",
                "sector": "peripherals",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2021, 1, 28),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["smart card reader", "iso 7816", "nfc reader", "e-passport", "smart card"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            },
            {
                "is_number": "IS 17650 : 2022",
                "title": "Ruggedized Mobile Devices and Field Tablets for Industrial Use",
                "scope": "MIL-STD-810H drop test, thermal shock, and IP68 water immersion specifications for ruggedized laptops and tablets.",
                "domain": "Electronics & Information Technology",
                "category": "Commercial Laptop & Notebook Computers",
                "sector": "laptops",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 3, 15),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["rugged tablet", "rugged laptop", "mil-std-810h", "field laptop", "industrial tablet"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 17700 : 2022",
                "title": "Power Line Communication (PLC) Modems for Smart Energy Distribution",
                "scope": "Physical layer and MAC protocol standards for Power Line Communication (PLC) data transmission over electricity grids.",
                "domain": "Electrical Engineering",
                "category": "Smart Meters & Power Grid Communications",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 7, 22),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["plc modem", "power line communication", "smart grid", "telecom"],
                "issuing_committee": "ETD 13 Electrical Instruments and Metering",
                "ic_code": "ETD13"
            },
            {
                "is_number": "IS 17800 : 2022",
                "title": "Technical Requirements for Wireless Access Points and Wi-Fi 6 Routers",
                "scope": "Electromagnetic compatibility (EMC), SAR emissions, and Wi-Fi 6/6E (802.11ax) radio specifications for government enterprise Wi-Fi APs.",
                "domain": "Electronics & Information Technology",
                "category": "Networking & LAN Infrastructure",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2022, 9, 30),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["wi-fi router", "access point", "wifi 6", "wireless router", "networking"],
                "issuing_committee": "LITD 18 Telecommunications and Broadband",
                "ic_code": "LITD18"
            },
            {
                "is_number": "IS 17990 : 2023",
                "title": "Safety Requirements for Drone Electronics and Unmanned Aerial Vehicle (UAV) Controllers",
                "scope": "Battery management, flight controller hardware security, and radio frequency control link standards for commercial UAVs under DGCA.",
                "domain": "Electronics & Information Technology",
                "category": "Smart Wearables & Consumer Electronics",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2023, 1, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["drone electronics", "uav controller", "drone battery", "dgca"],
                "issuing_committee": "LITD 07 Audio, Video and Similar Electronic Apparatus",
                "ic_code": "LITD07"
            },
            {
                "is_number": "IS 18050 : 2023",
                "title": "USB Type-C Power Delivery and Data Interface Specifications for Electronic Devices",
                "scope": "Mandatory interoperability, USB-PD power profile (up to 240W), and physical durability requirements for USB Type-C adaptors and cables.",
                "domain": "Electronics & Information Technology",
                "category": "Batteries, Laptops & Mobile Power Banks",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2023, 4, 18),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["usb-c", "type-c", "power delivery", "usb charger", "laptop charger"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 18100 : 2023",
                "title": "Specification for Semiconductor Integrated Circuits and Microcontrollers for Automotive & Industrial Use",
                "scope": "Qualification standards for microcontroller ICs, memory modules, and power management ICs (PMIC) manufactured under Make in India.",
                "domain": "Electronics & Information Technology",
                "category": "Computers, Servers & Enterprise IT Equipment",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2023, 6, 25),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["semiconductor", "microcontroller", "integrated circuit", "pmic", "chipset"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 18200 : 2024",
                "title": "Edge Computing Gateways and Industrial IoT (IIoT) Hardware - Security Guidelines",
                "scope": "Hardware-root-of-trust, secure firmware OTA update, and surge immunity standards for Industrial IoT Edge Gateways.",
                "domain": "Electronics & Information Technology",
                "category": "Cybersecurity & Data Center Infrastructure",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2024, 2, 12),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["iiot", "edge gateway", "iot security", "firmware ota", "industrial iot"],
                "issuing_committee": "LITD 17 Information Security and Data Privacy",
                "ic_code": "LITD17"
            },
            {
                "is_number": "IS 18300 : 2024",
                "title": "Quantum-Resistant Cryptographic Hardware Accelerators and Security Modules",
                "scope": "Post-quantum cryptography (PQC) hardware acceleration and key storage standards for critical infrastructure e-Governance servers.",
                "domain": "Electronics & Information Technology",
                "category": "Cybersecurity, Cloud & Data Protection",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2024, 5, 20),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["post quantum", "hsm", "cryptographic chip", "quantum security", "e-governance"],
                "issuing_committee": "LITD 17 Information Security and Data Privacy",
                "ic_code": "LITD17"
            },
            {
                "is_number": "IS 18400 : 2024",
                "title": "Thermal Management and Liquid Cooling Systems for High Performance AI Compute Servers",
                "scope": "Direct-to-chip liquid cooling and immersion cooling technical safety standards for AI Supercomputing Data Centers.",
                "domain": "Electronics & Information Technology",
                "category": "Enterprise Servers & Computer Hardware",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2024, 8, 15),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["liquid cooling", "ai server", "supercomputer", "data center cooling", "gpu server"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 18500 : 2025",
                "title": "Specification for Energy Efficient All-in-One (AIO) Desktop Computers",
                "scope": "Star-rating energy efficiency, integrated display safety, and eco-design recycling standards for All-in-One Desktop PCs.",
                "domain": "Electronics & Information Technology",
                "category": "Commercial Laptop & Notebook Computers",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2025, 1, 10),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["all-in-one pc", "aio desktop", "energy efficient pc", "desktop computer"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 18600 : 2025",
                "title": "Interactive Flat Panel Displays (IFPD) and Smart Interactive Whiteboards for Educational Institutions",
                "scope": "Toughened optical glass, anti-glare coating, multi-touch precision, and electrical safety standards for 65/75/86-inch Smart Whiteboards.",
                "domain": "Electronics & Information Technology",
                "category": "Monitors & Electronic Displays",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2025, 3, 20),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["ifpd", "smart whiteboard", "interactive display", "touch panel", "classroom display"],
                "issuing_committee": "LITD 07 Audio, Video and Similar Electronic Apparatus",
                "ic_code": "LITD07"
            },
            {
                "is_number": "IS 18700 : 2025",
                "title": "Technical Requirements for Enterprise 5G Private Network CPE Devices and Routers",
                "scope": "Frequency spectrum compliance, e-SIM profile management, and throughput benchmarks for 5G Private Network Customer Premise Equipment (CPE).",
                "domain": "Electronics & Information Technology",
                "category": "Networking & LAN Infrastructure",
                "sector": "telecom",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2025, 5, 15),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["5g router", "5g cpe", "private 5g", "telecom router", "networking"],
                "issuing_committee": "LITD 18 Telecommunications and Broadband",
                "ic_code": "LITD18"
            },
            {
                "is_number": "IS 18800 : 2025",
                "title": "Specification for High Efficiency GaN (Gallium Nitride) Power Adaptors for Portable Electronics",
                "scope": "Ultra-compact Gallium Nitride (GaN) fast charger safety, thermal dissipation, and harmonic emission limits for laptop and tablet adaptors.",
                "domain": "Electronics & Information Technology",
                "category": "Batteries, Laptops & Mobile Power Banks",
                "sector": "batteries_chargers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2025, 7, 30),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["gan charger", "gallium nitride", "fast adaptor", "laptop adaptor", "power supply"],
                "issuing_committee": "LITD 14 Information Technology Equipment Safety",
                "ic_code": "LITD14"
            },
            {
                "is_number": "IS 18900 : 2025",
                "title": "Essential Cybersecurity & Data Privacy Requirements for Smart Home IoT Appliances",
                "scope": "Default password removal, vulnerability disclosure, and encrypted wireless telemetry specifications for Smart Home IoT devices.",
                "domain": "Electronics & Information Technology",
                "category": "Cybersecurity & Data Center Infrastructure",
                "sector": "electronics",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2025, 9, 14),
                "certification_requirement": CertificationRequirement.CRS,
                "is_crs_mandated": True,
                "is_revised": False,
                "keywords": ["smart home iot", "iot security", "data privacy", "connected devices"],
                "issuing_committee": "LITD 17 Information Security and Data Privacy",
                "ic_code": "LITD17"
            },
            {
                "is_number": "IS 19000 : 2025",
                "title": "Technical Requirements for High Density Optical Storage Systems and Tape Libraries",
                "scope": "Archival longevity (50+ years), error correcting code (ECC), and tape drive robotic automation standards for government long-term digital preservation.",
                "domain": "Electronics & Information Technology",
                "category": "Solid State Drives & Storage Hardware",
                "sector": "computers",
                "status": StandardStatus.ACTIVE,
                "revision_date": date(2025, 11, 1),
                "certification_requirement": CertificationRequirement.MANDATORY,
                "is_crs_mandated": False,
                "is_revised": False,
                "keywords": ["tape library", "archival storage", "optical storage", "digital preservation"],
                "issuing_committee": "LITD 16 Computer Hardware and Peripherals",
                "ic_code": "LITD16"
            }
        ]

        for std_data in sample_standards:
            stmt = select(Standard).where(Standard.is_number == std_data["is_number"])
            res = await session.execute(stmt)
            existing_std = res.scalar_one_or_none()
            if not existing_std:
                std = Standard(**std_data)
                session.add(std)
                await session.flush()
                
                # Version
                ver = StandardVersion(
                    standard_id=std.id,
                    version_number="v1.0",
                    publication_date=std.revision_date or date(2020, 1, 1),
                    summary_of_changes="Latest mandatory revision under BIS Compulsory Registration Scheme."
                )
                session.add(ver)

                # Amendment
                am = Amendment(
                    standard_id=std.id,
                    amendment_number=1,
                    release_date=date(2023, 1, 1),
                    title="Amendment No. 1 to IS Standard",
                    description="Updated safety limits and language support guidelines."
                )
                session.add(am)

        await session.commit()
        print("[OK] Seeded Sample & CRS Mandatory BIS Standards, Versions, and Amendments.")
        print("[SUCCESS] Database Seeding Completed Successfully!")


if __name__ == "__main__":
    asyncio.run(seed_data())
