"""add_sector_and_committee_to_standards

Revision ID: f2bbd3204862
Revises: '001_initial_schema'
Create Date: 2026-09-03 06:43:22.169490+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bbd3204862'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_amendments_id'), 'amendments', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_compliance_profiles_id'), 'compliance_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_constraint(op.f('organizations_code_key'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.drop_constraint(op.f('product_categories_name_key'), 'product_categories', type_='unique')
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_index(op.f('ix_products_hs_code'), 'products', ['hs_code'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_standard_versions_id'), 'standard_versions', ['id'], unique=False)
    op.add_column('standards', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('standards', sa.Column('latest_amendment_date', sa.Date(), nullable=True))
    op.add_column('standards', sa.Column('is_crs_mandated', sa.Boolean(), nullable=False))
    op.add_column('standards', sa.Column('is_revised', sa.Boolean(), nullable=False))
    op.add_column('standards', sa.Column('superseded_by', sa.String(length=100), nullable=True))
    op.add_column('standards', sa.Column('last_scraped_at', sa.Date(), nullable=True))
    op.drop_constraint(op.f('standards_is_number_key'), 'standards', type_='unique')
    op.drop_index(op.f('ix_standards_is_number'), table_name='standards')
    op.create_index(op.f('ix_standards_is_number'), 'standards', ['is_number'], unique=True)
    op.create_index(op.f('ix_standards_id'), 'standards', ['id'], unique=False)
    op.create_index(op.f('ix_standards_sector'), 'standards', ['sector'], unique=False)
    op.drop_constraint(op.f('tenders_reference_number_key'), 'tenders', type_='unique')
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_reference_number'), 'tenders', ['reference_number'], unique=True)
    op.create_index(op.f('ix_tenders_title'), 'tenders', ['title'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tenders_title'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_reference_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.create_unique_constraint(op.f('tenders_reference_number_key'), 'tenders', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_standards_sector'), table_name='standards')
    op.drop_index(op.f('ix_standards_id'), table_name='standards')
    op.drop_index(op.f('ix_standards_is_number'), table_name='standards')
    op.create_index(op.f('ix_standards_is_number'), 'standards', ['is_number'], unique=False)
    op.create_unique_constraint(op.f('standards_is_number_key'), 'standards', ['is_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('standards', 'last_scraped_at')
    op.drop_column('standards', 'superseded_by')
    op.drop_column('standards', 'is_revised')
    op.drop_column('standards', 'is_crs_mandated')
    op.drop_column('standards', 'latest_amendment_date')
    op.drop_column('standards', 'sector')
    op.drop_index(op.f('ix_standard_versions_id'), table_name='standard_versions')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_hs_code'), table_name='products')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.create_unique_constraint(op.f('product_categories_name_key'), 'product_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=False)
    op.create_unique_constraint(op.f('organizations_code_key'), 'organizations', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_compliance_profiles_id'), table_name='compliance_profiles')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_amendments_id'), table_name='amendments')
    # ### end Alembic commands ###
